[package]
name = "OPL-VM"
version = "0.1.0"
edition = "2021"

[lib]
name = "oplvm"
path = "src/lib.rs"

[[bin]]
name = "opl"

[dependencies]
anyhow = "1.0.69"
byteorder = "1.4.3"
clap = "4.1.8"
env_logger = "0.10.0"
futures = "0.3.26"
log = "0.4.17"
thiserror = "1.0.38"
tokio = "1.25.0"
