[package]
name = "OPL-VM"
version = "0.1.0"
edition = "2021"

[lib]
name = "oplvm"
path = "src/lib.rs"

[[bin]]
name = "opl"

[dependencies]
anyhow = "1.0.71"
byteorder = "1.4.3"
clap = "4.3.0"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.19"
thiserror = "1.0.40"
tokio = "1.28.1"
