[package]
name = "OPL-VM"
version = "0.1.0"
edition = "2021"

[lib]
name = "oplvm"
path = "src/lib.rs"

[[bin]]
name = "opl"

[dependencies]
anyhow = "1.0.70"
byteorder = "1.4.3"
clap = "4.2.1"
env_logger = "0.10.0"
futures = "0.3.27"
log = "0.4.17"
thiserror = "1.0.40"
tokio = "1.26.0"
